import { BoardSpace, Challenge } from './types';

export const PLAYER_COLORS = [
    'bg-red-500', 'bg-blue-500', 'bg-green-500', 'bg-yellow-500'
];

export const BOARD_LAYOUT: BoardSpace[] = [
    { type: 'start', title: 'Início' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'unlucky', title: 'Azar' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'unlucky', title: 'Azar' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'unlucky', title: 'Azar' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'lucky', title: 'Sorte' },
    { type: 'challenge', title: 'Desafio' },
    { type: 'safe', title: 'Descanso' },
    { type: 'unlucky', title: 'Azar' },
    { type: 'finish', title: 'Chegada' },
];

export const CHALLENGES: Challenge[] = [
  // Easy
  { id: 1, question: "x + 1 = 3", getSolution: () => 2 },
  { id: 2, question: "x - 2 = 2", getSolution: () => 4 },
  { id: 3, question: "2x = 6", getSolution: () => 3 },
  { id: 4, question: "x / 2 = 4", getSolution: () => 8 },
  { id: 5, question: "x + 5 = 10", getSolution: () => 5 },
  { id: 6, question: "10 - x = 7", getSolution: () => 3 },
  { id: 7, question: "3x = 9", getSolution: () => 3 },
  { id: 8, question: "x / 3 = 3", getSolution: () => 9 },
  // Medium
  { id: 9, question: "2x + 1 = 11", getSolution: () => 5 },
  { id: 10, question: "15 - x = 8", getSolution: () => 7 },
  { id: 11, question: "x / 5 = 5", getSolution: () => 25 },
  { id: 12, question: "4x - 3 = 13", getSolution: () => 4 },
  // Hard
  { id: 13, question: "3x + 7 = 1", getSolution: () => -2 },
  { id: 14, question: "2x - 5 = -11", getSolution: () => -3 },
  { id: 15, question: "50 - 5x = 10", getSolution: () => 8 },
  { id: 16, question: "x / 4 + 2 = 5", getSolution: () => 12 },
  { id: 17, question: "-2x + 3 = 15", getSolution: () => -6 },
  { id: 18, question: "(x / 2) - 1 = 5", getSolution: () => 12 },
  { id: 19, question: "7 - x = 12", getSolution: () => -5 },
  { id: 20, question: "4x + 9 = 1", getSolution: () => -2 },
];